# Generated by Django 2.1 on 2018-08-13 17:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_contact_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: 999-999-9999', regex='^\\d{3}\\-\\d{3}\\-\\d{4}')])),
                ('secondary_contact_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: 999-999-9999', regex='^\\d{3}\\-\\d{3}\\-\\d{4}')])),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
