# Generated by Django 2.1 on 2018-08-13 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_guardian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='address',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='primary_contact_number',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='secondary_contact_number',
        ),
    ]
