# Generated by Django 2.1 on 2018-08-13 17:47

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_auto_20180813_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardian',
            name='primary_contact_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: 999-999-9999', regex='^\\d{3}\\-\\d{3}\\-\\d{4}')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardian',
            name='secondary_contact_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: 999-999-9999', regex='^\\d{3}\\-\\d{3}\\-\\d{4}')]),
            preserve_default=False,
        ),
    ]
