# Generated by Django 2.1 on 2018-08-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='type',
            field=models.CharField(default='tbd', max_length=250),
            preserve_default=False,
        ),
    ]
