# Generated by Django 2.1 on 2018-08-04 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_program_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('prerequisite', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='program',
            name='description',
        ),
        migrations.RemoveField(
            model_name='program',
            name='level',
        ),
        migrations.RemoveField(
            model_name='program',
            name='prerequisite',
        ),
        migrations.RemoveField(
            model_name='program',
            name='type',
        ),
        migrations.AlterField(
            model_name='iteration',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.ProgramLevel'),
        ),
        migrations.AddField(
            model_name='programlevel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Program'),
        ),
    ]
