# Generated by Django 2.1 on 2018-08-04 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_auto_20180804_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programlevel',
            old_name='type',
            new_name='category',
        ),
    ]
